"""Home grounds for the six European leagues (B-7, audit #2).

openfootball fixtures carry no venue, so previews, calendar events and the kickoff weather had
nothing to show for these leagues. Keyed by the club name exactly as data/<lg>/games.csv spells
it (engsoccerdata's names); value is (stadium, city). Clubs outside the current top flight are
included where they are likely to come back up, so a promotion doesn't leave a blank.
"""

VENUES = {
    "epl": {
        "AFC Bournemouth": ("Vitality Stadium", "Bournemouth"),
        "Arsenal": ("Emirates Stadium", "London"),
        "Aston Villa": ("Villa Park", "Birmingham"),
        "Brentford": ("Gtech Community Stadium", "London"),
        "Brighton & Hove Albion": ("American Express Stadium", "Brighton"),
        "Burnley": ("Turf Moor", "Burnley"),
        "Chelsea": ("Stamford Bridge", "London"),
        "Coventry City": ("Coventry Building Society Arena", "Coventry"),
        "Crystal Palace": ("Selhurst Park", "London"),
        "Everton": ("Hill Dickinson Stadium", "Liverpool"),
        "Fulham": ("Craven Cottage", "London"),
        "Hull City": ("MKM Stadium", "Hull"),
        "Ipswich Town": ("Portman Road", "Ipswich"),
        "Leeds United": ("Elland Road", "Leeds"),
        "Leicester City": ("King Power Stadium", "Leicester"),
        "Liverpool": ("Anfield", "Liverpool"),
        "Manchester City": ("Etihad Stadium", "Manchester"),
        "Manchester United": ("Old Trafford", "Manchester"),
        "Middlesbrough": ("Riverside Stadium", "Middlesbrough"),
        "Newcastle United": ("St James' Park", "Newcastle upon Tyne"),
        "Norwich City": ("Carrow Road", "Norwich"),
        "Nottingham Forest": ("The City Ground", "Nottingham"),
        "Sheffield United": ("Bramall Lane", "Sheffield"),
        "Southampton": ("St Mary's Stadium", "Southampton"),
        "Sunderland": ("Stadium of Light", "Sunderland"),
        "Tottenham Hotspur": ("Tottenham Hotspur Stadium", "London"),
        "West Bromwich Albion": ("The Hawthorns", "West Bromwich"),
        "West Ham United": ("London Stadium", "London"),
        "Wolverhampton Wanderers": ("Molineux Stadium", "Wolverhampton"),
    },
    "laliga": {
        "Athletic Bilbao": ("San Mamés", "Bilbao"),
        "Atletico Madrid": ("Riyadh Air Metropolitano", "Madrid"),
        "CA Osasuna": ("El Sadar", "Pamplona"),
        "CD Alaves": ("Mendizorrotza", "Vitoria-Gasteiz"),
        "CD Leganes": ("Estadio Municipal de Butarque", "Leganés"),
        "Celta Vigo": ("Abanca-Balaídos", "Vigo"),
        "Deportivo La Coruna": ("Riazor", "A Coruña"),
        "Elche CF": ("Estadio Martínez Valero", "Elche"),
        "Espanyol Barcelona": ("RCDE Stadium", "Cornellà de Llobregat"),
        "FC Barcelona": ("Spotify Camp Nou", "Barcelona"),
        "Getafe CF": ("Estadio Coliseum", "Getafe"),
        "Girona FC": ("Estadi Montilivi", "Girona"),
        "Levante UD": ("Estadi Ciutat de València", "Valencia"),
        "Malaga CF": ("La Rosaleda", "Málaga"),
        "RCD Mallorca": ("Estadi Mallorca Son Moix", "Palma"),
        "Racing Santander": ("El Sardinero", "Santander"),
        "Rayo Vallecano": ("Estadio de Vallecas", "Madrid"),
        "Real Betis": ("Estadio de La Cartuja", "Seville"),
        "Real Madrid": ("Santiago Bernabéu", "Madrid"),
        "Real Oviedo": ("Estadio Carlos Tartiere", "Oviedo"),
        "Real Sociedad": ("Reale Arena", "San Sebastián"),
        "Real Valladolid": ("Estadio José Zorrilla", "Valladolid"),
        "Sevilla FC": ("Ramón Sánchez-Pizjuán", "Seville"),
        "UD Las Palmas": ("Estadio Gran Canaria", "Las Palmas"),
        "Valencia CF": ("Mestalla", "Valencia"),
        "Villarreal CF": ("Estadio de la Cerámica", "Villarreal"),
    },
    "seriea": {
        "AC Milan": ("San Siro", "Milan"),
        "AC Monza": ("U-Power Stadium", "Monza"),
        "AC Venezia": ("Stadio Pier Luigi Penzo", "Venice"),
        "ACF Fiorentina": ("Stadio Artemio Franchi", "Florence"),
        "AS Roma": ("Stadio Olimpico", "Rome"),
        "Atalanta": ("Gewiss Stadium", "Bergamo"),
        "Bologna FC": ("Stadio Renato Dall'Ara", "Bologna"),
        "Cagliari Calcio": ("Unipol Domus", "Cagliari"),
        "Como Calcio": ("Stadio Giuseppe Sinigaglia", "Como"),
        "Empoli FC": ("Stadio Carlo Castellani", "Empoli"),
        "Frosinone Calcio": ("Stadio Benito Stirpe", "Frosinone"),
        "Genoa CFC": ("Stadio Luigi Ferraris", "Genoa"),
        "Hellas Verona": ("Stadio Marcantonio Bentegodi", "Verona"),
        "Inter": ("San Siro", "Milan"),
        "Juventus": ("Allianz Stadium", "Turin"),
        "Lazio Roma": ("Stadio Olimpico", "Rome"),
        "Parma FC": ("Stadio Ennio Tardini", "Parma"),
        "Pisa SC": ("Arena Garibaldi", "Pisa"),
        "SSC Napoli": ("Stadio Diego Armando Maradona", "Naples"),
        "Sassuolo Calcio": ("Mapei Stadium", "Reggio Emilia"),
        "Torino FC": ("Stadio Olimpico Grande Torino", "Turin"),
        "US Cremonese": ("Stadio Giovanni Zini", "Cremona"),
        "US Lecce": ("Stadio Via del Mare", "Lecce"),
        "Udinese Calcio": ("Bluenergy Stadium", "Udine"),
    },
    "bundesliga": {
        "1. FC Heidenheim": ("Voith-Arena", "Heidenheim"),
        "1. FC Koln": ("RheinEnergieStadion", "Cologne"),
        "1. FC Union Berlin": ("Stadion An der Alten Försterei", "Berlin"),
        "1. FSV Mainz 05": ("Mewa Arena", "Mainz"),
        "1899 Hoffenheim": ("PreZero Arena", "Sinsheim"),
        "Bayer Leverkusen": ("BayArena", "Leverkusen"),
        "Bayern Munchen": ("Allianz Arena", "Munich"),
        "Bor. Monchengladbach": ("Borussia-Park", "Mönchengladbach"),
        "Borussia Dortmund": ("Signal Iduna Park", "Dortmund"),
        "Eintracht Frankfurt": ("Deutsche Bank Park", "Frankfurt"),
        "FC Augsburg": ("WWK Arena", "Augsburg"),
        "FC Schalke 04": ("Veltins-Arena", "Gelsenkirchen"),
        "FC St. Pauli": ("Millerntor-Stadion", "Hamburg"),
        "Hamburger SV": ("Volksparkstadion", "Hamburg"),
        "Holstein Kiel": ("Holstein-Stadion", "Kiel"),
        "RasenBallsport Leipzig": ("Red Bull Arena", "Leipzig"),
        "SC Freiburg": ("Europa-Park Stadion", "Freiburg"),
        "SC Paderborn 07": ("Home Deluxe Arena", "Paderborn"),
        "SV Elversberg": ("Ursapark", "Spiesen-Elversberg"),
        "VfB Stuttgart": ("MHPArena", "Stuttgart"),
        "VfL Bochum": ("Vonovia Ruhrstadion", "Bochum"),
        "VfL Wolfsburg": ("Volkswagen Arena", "Wolfsburg"),
        "Werder Bremen": ("Weserstadion", "Bremen"),
    },
    "ligue1": {
        "AJ Auxerre": ("Stade de l'Abbé-Deschamps", "Auxerre"),
        "AS Monaco": ("Stade Louis II", "Monaco"),
        "AS Saint-Etienne": ("Stade Geoffroy-Guichard", "Saint-Étienne"),
        "Angers SCO": ("Stade Raymond Kopa", "Angers"),
        "ESTAC Troyes": ("Stade de l'Aube", "Troyes"),
        "FC Lorient": ("Stade du Moustoir", "Lorient"),
        "FC Metz": ("Stade Saint-Symphorien", "Metz"),
        "FC Nantes": ("Stade de la Beaujoire", "Nantes"),
        "Le Havre AC": ("Stade Océane", "Le Havre"),
        "Le Mans UC 72": ("MMArena", "Le Mans"),
        "Lille OSC": ("Stade Pierre-Mauroy", "Villeneuve-d'Ascq"),
        "Montpellier HSC": ("Stade de la Mosson", "Montpellier"),
        "OGC Nice": ("Allianz Riviera", "Nice"),
        "Olympique Lyon": ("Groupama Stadium", "Décines-Charpieu"),
        "Olympique Marseille": ("Stade Vélodrome", "Marseille"),
        "Paris FC": ("Stade Jean-Bouin", "Paris"),
        "Paris Saint-Germain": ("Parc des Princes", "Paris"),
        "RC Lens": ("Stade Bollaert-Delelis", "Lens"),
        "RC Strasbourg": ("Stade de la Meinau", "Strasbourg"),
        "Stade Brest": ("Stade Francis-Le Blé", "Brest"),
        "Stade Reims": ("Stade Auguste-Delaune", "Reims"),
        "Stade Rennes": ("Roazhon Park", "Rennes"),
        "Toulouse FC": ("Stadium de Toulouse", "Toulouse"),
    },
    "eredivisie": {
        "ADO Den Haag": ("Bingoal Stadion", "The Hague"),
        "AFC Ajax": ("Johan Cruijff ArenA", "Amsterdam"),
        "AZ Alkmaar": ("AFAS Stadion", "Alkmaar"),
        "Almere City FC": ("Yanmar Stadion", "Almere"),
        "FC Groningen": ("Euroborg", "Groningen"),
        "FC Twente": ("De Grolsch Veste", "Enschede"),
        "FC Utrecht": ("Stadion Galgenwaard", "Utrecht"),
        "FC Volendam": ("Kras Stadion", "Volendam"),
        "Feyenoord": ("De Kuip", "Rotterdam"),
        "Fortuna Sittard": ("Fortuna Sittard Stadion", "Sittard"),
        "Go Ahead Eagles": ("De Adelaarshorst", "Deventer"),
        "Heracles Almelo": ("Erve Asito", "Almelo"),
        "NAC Breda": ("Rat Verlegh Stadion", "Breda"),
        "NEC Nijmegen": ("Goffertstadion", "Nijmegen"),
        "PEC Zwolle": ("MAC³PARK Stadion", "Zwolle"),
        "PSV Eindhoven": ("Philips Stadion", "Eindhoven"),
        "RKC Waalwijk": ("Mandemakers Stadion", "Waalwijk"),
        "SBV Excelsior": ("Van Donge & De Roo Stadion", "Rotterdam"),
        "SC Cambuur": ("Cambuur Stadion", "Leeuwarden"),
        "Sparta Rotterdam": ("Het Kasteel", "Rotterdam"),
        "Telstar": ("BUKO Stadion", "Velsen-Zuid"),
        "Willem II": ("Koning Willem II Stadion", "Tilburg"),
        "sc Heerenveen": ("Abe Lenstra Stadion", "Heerenveen"),
    },
}
